### ISSUE TITLE
[Bug] MS Edge (Chromium) download says "Virus detected"

### ISSUE THREAD

**Issue by Tyler887** [liweiyi88/gosnakego#1]
I tried to download, but it comes up with `Download failed - Virus detected`. Try exporting the Windows version of the binary as `gosnakego.exe`.

**Comment by liweiyi88** [comment]
@Tyler887, I have made a new release with `.exe` extension for windows binary. Feel free to close this ticket if it works for you. https://github.com/liweiyi88/gosnakego/releases/tag/v0.1.1

**Comment by Tyler887** [comment]
It works now! :+1:

However, I have now downloaded on Chrome, but it says that "it is not commonly downloaded".
