### ISSUE TITLE
Asset for Linux wasn't released in v0.3.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [liweiyi88/gosnakego#7]
An asset for Linux wasn't released in v0.3.0.

https://github.com/liweiyi88/gosnakego/releases/tag/v0.3.0

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/13323303/210768907-3ea53910-4b72-425a-ba05-2dc5e81976e9.png">

I guess this isn't intentional but a bug or something.

**Comment by liweiyi88** [comment]
yes, it is due to the cross-compile issue in the beep package https://github.com/faiface/beep/issues/74. Maybe I shall build the Linux binary from a VM. But for now, you can just build the binary from the source if you want to play with it on a Linux machine. 🙏

**Comment by suzuki-shunsuke** [comment]
I understood. Thank you for your explanation.
